libosip: oSIP cseq header definition.
oSIP cseq header definition.
oSIP headers definitions
Classes
struct osip_cseq
Typedefs
typedef struct osip_cseq osip_cseq_t
Functions
int osip_cseq_init (osip_cseq_t **header)
void osip_cseq_free (osip_cseq_t *header)
int osip_cseq_parse (osip_cseq_t *header, const char *hvalue)
int osip_cseq_to_str (const osip_cseq_t *header, char **dest)
int osip_cseq_clone (const osip_cseq_t *header, osip_cseq_t **dest)
void osip_cseq_set_number (osip_cseq_t *header, char *value)
char * osip_cseq_get_number (osip_cseq_t *header)
void osip_cseq_set_method (osip_cseq_t *header, char *value)
char * osip_cseq_get_method (osip_cseq_t *header)
int osip_cseq_match (osip_cseq_t *cseq1, osip_cseq_t *cseq2)
Detailed Description
Typedef Documentation
osip_cseq_t
Structure for CSeq headers.
Function Documentation
int osip_cseq_clone (const osip_cseq_t * header, osip_cseq_t ** dest)
Clone a CSeq element.
Parameters
header The element to work on.
dest A pointer on the copy of the element.
References osip_cseq::method, osip_cseq::number, osip_cseq_free(), and osip_cseq_init().
Referenced by osip_message_clone().
void osip_cseq_free (osip_cseq_t * header)
Free a CSeq element.
Parameters
header The element to work on.
References osip_cseq::method, and osip_cseq::number.
Referenced by osip_cseq_clone(), osip_message_free(), osip_message_set_cseq(), and osip_transaction_free2().
char* osip_cseq_get_method (osip_cseq_t * header)
Get the method from a CSeq header.
Parameters
header The element to work on.
References osip_cseq::method.
char* osip_cseq_get_number (osip_cseq_t * header)
Get the number from a CSeq header.
Parameters
header The element to work on.
References osip_cseq::number.
int osip_cseq_init (osip_cseq_t ** header)
Allocate a CSeq element.
Parameters
header The element to work on.
Referenced by osip_cseq_clone(), and osip_message_set_cseq().
int osip_cseq_match (osip_cseq_t * cseq1, osip_cseq_t * cseq2)
Check if the CSeq headers match. NOTE: THIS IS AN INTERNAL METHOD ONLY
Parameters
cseq1 The initial CSeq header.
cseq2 The new CSeq header.
References osip_cseq::method, and osip_cseq::number.
int osip_cseq_parse (osip_cseq_t * header, const char * hvalue)
Parse a CSeq element.
Parameters
header The element to work on.
hvalue The string to parse.
References osip_cseq::method, and osip_cseq::number.
Referenced by osip_message_set_cseq().
void osip_cseq_set_method (osip_cseq_t * header, char * value)
Set the method in the CSeq element.
Parameters
header The element to work on.
value The value of the element.
References osip_cseq::method.
void osip_cseq_set_number (osip_cseq_t * header, char * value)
Set the number in the CSeq element.
Parameters
header The element to work on.
value The value of the element.
References osip_cseq::number.
int osip_cseq_to_str (const osip_cseq_t * header, char ** dest)
Get a string representation of a CSeq element.
Parameters
header The element to work on.
dest A pointer on the new allocated string.
References osip_cseq::method, and osip_cseq::number.