libosip: oSIP semaphore definitions
oSIP semaphore definitions
Classes
struct osip_sem
Functions
struct osip_sem * osip_sem_init (unsigned int value)
int osip_sem_destroy (struct osip_sem *sem)
int osip_sem_post (struct osip_sem *sem)
int osip_sem_wait (struct osip_sem *sem)
int osip_sem_trywait (struct osip_sem *sem)
Detailed Description
Function Documentation
int osip_sem_destroy (struct osip_sem * sem)
Destroy a semaphore.
Parameters
sem The semaphore to destroy.
Referenced by osip_fifo_free().
struct osip_sem* osip_sem_init (unsigned int value) read
Allocate and Initialise a semaphore.
Parameters
value The initial value for the semaphore.
Referenced by osip_fifo_init().
int osip_sem_post (struct osip_sem * sem)
Post operation on a semaphore.
Parameters
sem The semaphore to destroy.
Referenced by osip_fifo_add(), and osip_fifo_insert().
int osip_sem_trywait (struct osip_sem * sem)
Wait operation on a semaphore. NOTE: if the semaphore is at 0, this call won't block.
Parameters
sem The semaphore to destroy.
Referenced by osip_fifo_tryget().
int osip_sem_wait (struct osip_sem * sem)
Wait operation on a semaphore. NOTE: this call will block if the semaphore is at 0.
Parameters
sem The semaphore to destroy.
Referenced by osip_fifo_get().