libosip: oSIP record-route header definition.
oSIP record-route header definition.
oSIP headers definitions
Macros
#define osip_record_route_clone osip_from_clone
#define osip_record_route_set_url(header, url) osip_from_set_url((osip_from_t*)header,url)
#define osip_record_route_get_url(header) osip_from_get_url((osip_from_t*)header)
#define osip_record_route_param_get(header, pos, dest) osip_from_param_get((osip_from_t*)header,pos,dest)
#define osip_record_route_param_add(header, name, value) osip_generic_param_add((&(header)->gen_params),name,value)
#define osip_record_route_param_get_byname(header, name, dest) osip_generic_param_get_byname((&(header)->gen_params),name,dest)
Typedefs
typedef osip_from_t osip_record_route_t
Functions
int osip_record_route_init (osip_record_route_t **header)
void osip_record_route_free (osip_record_route_t *header)
int osip_record_route_parse (osip_record_route_t *header, const char *hvalue)
int osip_record_route_to_str (const osip_record_route_t *header, char **dest)
Detailed Description
Macro Definition Documentation
#define osip_record_route_clone osip_from_clone
Clone a Record-Route element.
Parameters
header The element to work on.
dest A pointer on the copy of the element.
Referenced by osip_dialog_update_route_set_as_uac(), and osip_message_clone().
#define osip_record_route_get_url (header) osip_from_get_url((osip_from_t*)header)
Get the url from a Record-Route header.
Parameters
header The element to work on.
#define osip_record_route_param_add (header, name, value) osip_generic_param_add((&(header)->gen_params),name,value)
Allocate and add a generic parameter element in a list.
Parameters
header The element to work on.
name The token name.
value The token value.
#define osip_record_route_param_get (header, pos, dest) osip_from_param_get((osip_from_t*)header,pos,dest)
Get a header parameter from a Record-Route element.
Parameters
header The element to work on.
pos The index of the element to get.
dest A pointer on the element found.
#define osip_record_route_param_get_byname (header, name, dest) osip_generic_param_get_byname((&(header)->gen_params),name,dest)
Find a header parameter in a Record-Route element.
Parameters
header The element to work on.
name The token name to search.
dest A pointer on the element found.
#define osip_record_route_set_url (header, url) osip_from_set_url((osip_from_t*)header,url)
Set the url in the Record-Route element.
Parameters
header The element to work on.
url The value of the element.
Typedef Documentation
osip_record_route_t
Structure for Record-Route headers.
Function Documentation
void osip_record_route_free (osip_record_route_t * header)
Free a Record-Route element.
Parameters
header The element to work on.
References osip_from_free().
Referenced by osip_dialog_free(), osip_dialog_update_route_set_as_uac(), osip_message_free(), and osip_message_set_record_route().
int osip_record_route_init (osip_record_route_t ** header)
Allocate a Record-Route element.
Parameters
header The element to work on.
References osip_from_init().
Referenced by osip_message_set_record_route().
int osip_record_route_parse (osip_record_route_t * header, const char * hvalue)
Parse a Record-Route element.
Parameters
header The element to work on.
hvalue The string to parse.
References osip_from_parse().
Referenced by osip_message_set_record_route().
int osip_record_route_to_str (const osip_record_route_t * header, char ** dest)
Get a string representation of a Record-Route element.
Parameters
header The element to work on.
dest A pointer on the new allocated string.
References osip_from::displayname, osip_from::gen_params, osip_uri_param::gname, osip_uri_param::gvalue, osip_list_eol(), osip_list_get(), osip_uri_to_str(), and osip_from::url.
Referenced by osip_route_to_str().