libosip: oSIP www-authenticate header definition.
oSIP www-authenticate header definition.
oSIP headers definitions
Classes
struct osip_www_authenticate
Macros
#define osip_www_authenticate_set_stale_true(header) osip_www_authenticate_set_stale(header,osip_strdup("true"))
#define osip_www_authenticate_set_stale_false(header) osip_www_authenticate_set_stale(header,osip_strdup("false"))
#define osip_www_authenticate_set_algorithm_MD5(header) osip_www_authenticate_set_algorithm(header,osip_strdup("MD5"))
Typedefs
typedef struct
osip_www_authenticate osip_www_authenticate_t
Functions
int osip_www_authenticate_init (osip_www_authenticate_t **header)
int osip_www_authenticate_parse (osip_www_authenticate_t *header, const char *hvalue)
int osip_www_authenticate_to_str (const osip_www_authenticate_t *header, char **dest)
void osip_www_authenticate_free (osip_www_authenticate_t *header)
int osip_www_authenticate_clone (const osip_www_authenticate_t *header, osip_www_authenticate_t **dest)
char * osip_www_authenticate_get_auth_type (osip_www_authenticate_t *header)
void osip_www_authenticate_set_auth_type (osip_www_authenticate_t *header, char *value)
char * osip_www_authenticate_get_realm (osip_www_authenticate_t *header)
void osip_www_authenticate_set_realm (osip_www_authenticate_t *header, char *value)
char * osip_www_authenticate_get_domain (osip_www_authenticate_t *header)
void osip_www_authenticate_set_domain (osip_www_authenticate_t *header, char *value)
char * osip_www_authenticate_get_nonce (osip_www_authenticate_t *header)
void osip_www_authenticate_set_nonce (osip_www_authenticate_t *header, char *value)
char * osip_www_authenticate_get_opaque (osip_www_authenticate_t *header)
void osip_www_authenticate_set_opaque (osip_www_authenticate_t *header, char *value)
char * osip_www_authenticate_get_stale (osip_www_authenticate_t *header)
void osip_www_authenticate_set_stale (osip_www_authenticate_t *header, char *value)
char * osip_www_authenticate_get_algorithm (osip_www_authenticate_t *header)
void osip_www_authenticate_set_algorithm (osip_www_authenticate_t *header, char *value)
char * osip_www_authenticate_get_qop_options (osip_www_authenticate_t *header)
void osip_www_authenticate_set_qop_options (osip_www_authenticate_t *header, char *value)
Detailed Description
Macro Definition Documentation
#define osip_www_authenticate_set_algorithm_MD5 (header) osip_www_authenticate_set_algorithm(header,osip_strdup("MD5"))
Add the algorithm parameter set to "MD5" in a Www-Authenticate element.
Parameters
header The element to work on.
#define osip_www_authenticate_set_stale_false (header) osip_www_authenticate_set_stale(header,osip_strdup("false"))
Add a stale parameter set to "false" in a Www-Authenticate element.
Parameters
header The element to work on.
#define osip_www_authenticate_set_stale_true (header) osip_www_authenticate_set_stale(header,osip_strdup("true"))
Add a stale parameter set to "true" in a Www-Authenticate element.
Parameters
header The element to work on.
Typedef Documentation
osip_www_authenticate_t
Structure for WWW-Authenticate headers.
Function Documentation
int osip_www_authenticate_clone (const osip_www_authenticate_t * header, osip_www_authenticate_t ** dest)
Clone a Www-Authenticate element.
Parameters
header The element to work on.
dest A pointer on the copy of the element.
References osip_www_authenticate::algorithm, osip_www_authenticate::auth_type, osip_www_authenticate::domain, osip_www_authenticate::nonce, osip_www_authenticate::opaque, osip_www_authenticate_free(), osip_www_authenticate_init(), osip_www_authenticate::qop_options, osip_www_authenticate::realm, and osip_www_authenticate::stale.
Referenced by osip_message_clone().
void osip_www_authenticate_free (osip_www_authenticate_t * header)
Free a Www-Authenticate element.
Parameters
header The element to work on.
References osip_www_authenticate::algorithm, osip_www_authenticate::auth_type, osip_www_authenticate::domain, osip_www_authenticate::nonce, osip_www_authenticate::opaque, osip_www_authenticate::qop_options, osip_www_authenticate::realm, and osip_www_authenticate::stale.
Referenced by osip_message_free(), osip_message_set_www_authenticate(), and osip_www_authenticate_clone().
char* osip_www_authenticate_get_algorithm (osip_www_authenticate_t * header)
Get value of the algorithm parameter from a Www-Authenticate element.
Parameters
header The element to work on.
References osip_www_authenticate::algorithm.
char* osip_www_authenticate_get_auth_type (osip_www_authenticate_t * header)
Get value of the auth_type parameter from a Www-Authenticate element.
Parameters
header The element to work on.
References osip_www_authenticate::auth_type.
char* osip_www_authenticate_get_domain (osip_www_authenticate_t * header)
Get value of the domain parameter from a Www-Authenticate element.
Parameters
header The element to work on.
References osip_www_authenticate::domain.
char* osip_www_authenticate_get_nonce (osip_www_authenticate_t * header)
Get value of the nonce parameter from a Www-Authenticate element.
Parameters
header The element to work on.
References osip_www_authenticate::nonce.
char* osip_www_authenticate_get_opaque (osip_www_authenticate_t * header)
Get value of the opaque parameter from a Www-Authenticate element.
Parameters
header The element to work on.
References osip_www_authenticate::opaque.
char* osip_www_authenticate_get_qop_options (osip_www_authenticate_t * header)
Get value of the qop_options parameter from a Www-Authenticate element.
Parameters
header The element to work on.
References osip_www_authenticate::qop_options.
char* osip_www_authenticate_get_realm (osip_www_authenticate_t * header)
Get value of the realm parameter from a Www-Authenticate element.
Parameters
header The element to work on.
References osip_www_authenticate::realm.
char* osip_www_authenticate_get_stale (osip_www_authenticate_t * header)
Get value of the stale parameter from a Www-Authenticate element.
Parameters
header The element to work on.
References osip_www_authenticate::stale.
int osip_www_authenticate_init (osip_www_authenticate_t ** header)
Allocate a Www-Authenticate element.
Parameters
header The element to work on.
Referenced by osip_message_set_www_authenticate(), and osip_www_authenticate_clone().
int osip_www_authenticate_parse (osip_www_authenticate_t * header, const char * hvalue)
Parse a Www-Authenticate element.
Parameters
header The element to work on.
hvalue The string to parse.
References osip_www_authenticate::algorithm, osip_www_authenticate::auth_type, osip_www_authenticate::domain, osip_www_authenticate::nonce, osip_www_authenticate::opaque, osip_www_authenticate::qop_options, osip_www_authenticate::realm, and osip_www_authenticate::stale.
Referenced by osip_message_set_www_authenticate().
void osip_www_authenticate_set_algorithm (osip_www_authenticate_t * header, char * value)
Add the algorithm parameter in a Www-Authenticate element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_www_authenticate::algorithm.
void osip_www_authenticate_set_auth_type (osip_www_authenticate_t * header, char * value)
Add the auth_type parameter from a Www-Authenticate element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_www_authenticate::auth_type.
void osip_www_authenticate_set_domain (osip_www_authenticate_t * header, char * value)
Add the domain parameter from a Www-Authenticate element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_www_authenticate::domain.
void osip_www_authenticate_set_nonce (osip_www_authenticate_t * header, char * value)
Add the nonce parameter from a Www-Authenticate element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_www_authenticate::nonce.
void osip_www_authenticate_set_opaque (osip_www_authenticate_t * header, char * value)
Add the opaque parameter from a Www-Authenticate element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_www_authenticate::opaque.
void osip_www_authenticate_set_qop_options (osip_www_authenticate_t * header, char * value)
Add the qop_options parameter from a Www-Authenticate element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_www_authenticate::qop_options.
void osip_www_authenticate_set_realm (osip_www_authenticate_t * header, char * value)
Add the realm parameter from a Www-Authenticate element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_www_authenticate::realm.
void osip_www_authenticate_set_stale (osip_www_authenticate_t * header, char * value)
Add the stale parameter in a Www-Authenticate element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_www_authenticate::stale.
int osip_www_authenticate_to_str (const osip_www_authenticate_t * header, char ** dest)
Get a string representation of a Www-Authenticate element.
Parameters
header The element to work on.
dest A pointer on the new allocated string.
References osip_www_authenticate::algorithm, osip_www_authenticate::auth_type, osip_www_authenticate::domain, osip_www_authenticate::nonce, osip_www_authenticate::opaque, osip_www_authenticate::qop_options, osip_www_authenticate::realm, and osip_www_authenticate::stale.