libosip: oSIP content-length definition.
oSIP content-length definition.
oSIP headers definitions
Classes
struct osip_content_length
Typedefs
typedef struct osip_content_length osip_content_length_t
Functions
int osip_content_length_init (osip_content_length_t **header)
void osip_content_length_free (osip_content_length_t *header)
int osip_content_length_parse (osip_content_length_t *header, const char *hvalue)
int osip_content_length_to_str (const osip_content_length_t *header, char **dest)
int osip_content_length_clone (const osip_content_length_t *header, osip_content_length_t **dest)
Detailed Description
Typedef Documentation
osip_content_length_t
Structure for Content-Length headers.
Function Documentation
int osip_content_length_clone (const osip_content_length_t * header, osip_content_length_t ** dest)
Clone a Content-Length element.
Parameters
header The element to work on.
dest A pointer on the copy of the element.
References osip_content_length_free(), osip_content_length_init(), and osip_content_length::value.
Referenced by osip_message_clone().
void osip_content_length_free (osip_content_length_t * header)
Free a Content-Length element.
Parameters
header The element to work on.
References osip_content_length::value.
Referenced by osip_content_length_clone(), osip_message_free(), and osip_message_set_content_length().
int osip_content_length_init (osip_content_length_t ** header)
Allocate a Content-Length element.
Parameters
header The element to work on.
Referenced by osip_content_length_clone(), and osip_message_set_content_length().
int osip_content_length_parse (osip_content_length_t * header, const char * hvalue)
Parse a Content-Length element.
Parameters
header The element to work on.
hvalue The string to parse.
References osip_content_length::value.
Referenced by osip_message_set_content_length().
int osip_content_length_to_str (const osip_content_length_t * header, char ** dest)
Get a string representation of a Content-Length element.
Parameters
header The element to work on.
dest A pointer on the new allocated string.
References osip_content_length::value.