libosip: oSIP accept-encoding header definition.
oSIP accept-encoding header definition.
oSIP headers definitions
Classes
struct osip_accept_encoding
Macros
#define osip_accept_encoding_param_add(header, name, value) osip_generic_param_add((&(header)->gen_params),name,value)
#define osip_accept_encoding_param_get_byname(header, name, dest) osip_generic_param_get_byname((&(header)->gen_params),name,dest)
Typedefs
typedef struct osip_accept_encoding osip_accept_encoding_t
Functions
int osip_accept_encoding_init (osip_accept_encoding_t **header)
int osip_accept_encoding_parse (osip_accept_encoding_t *header, const char *hvalue)
int osip_accept_encoding_to_str (const osip_accept_encoding_t *header, char **dest)
void osip_accept_encoding_free (osip_accept_encoding_t *header)
int osip_accept_encoding_clone (const osip_accept_encoding_t *header, osip_accept_encoding_t **dest)
void osip_accept_encoding_set_element (osip_accept_encoding_t *header, char *value)
char * osip_accept_encoding_get_element (const osip_accept_encoding_t *header)
Detailed Description
Macro Definition Documentation
#define osip_accept_encoding_param_add (header, name, value) osip_generic_param_add((&(header)->gen_params),name,value)
Allocate and Add a header parameter in an Accept-Encoding element.
Parameters
header The element to work on.
name The token name for the new parameter.
value The token value for the new parameter.
#define osip_accept_encoding_param_get_byname (header, name, dest) osip_generic_param_get_byname((&(header)->gen_params),name,dest)
Find a header parameter in an Accept-Encoding element.
Parameters
header The element to work on.
name The token name to search.
dest A pointer on the element found.
Typedef Documentation
osip_accept_encoding_t
Structure for Accept-Encoding header.
Function Documentation
int osip_accept_encoding_clone (const osip_accept_encoding_t * header, osip_accept_encoding_t ** dest)
Clone a Accept-Encoding element.
Parameters
header The element to work on.
dest A pointer on the copy of the element.
References osip_accept_encoding::element, osip_accept_encoding::gen_params, osip_accept_encoding_free(), osip_accept_encoding_init(), osip_generic_param_clone, osip_list_add(), osip_list_eol(), and osip_list_get().
Referenced by osip_message_clone().
void osip_accept_encoding_free (osip_accept_encoding_t * header)
Free a Accept-Encoding element.
Parameters
header The element to work on.
References osip_accept_encoding::element, and osip_accept_encoding::gen_params.
Referenced by osip_accept_encoding_clone(), osip_message_free(), and osip_message_set_accept_encoding().
char* osip_accept_encoding_get_element (const osip_accept_encoding_t * header)
Get the value of an Accept-Encoding element.
Parameters
header The element to work on.
References osip_accept_encoding::element.
int osip_accept_encoding_init (osip_accept_encoding_t ** header)
Allocate a Accept-Encoding element.
Parameters
header The element to work on.
References osip_list_init().
Referenced by osip_accept_encoding_clone(), and osip_message_set_accept_encoding().
int osip_accept_encoding_parse (osip_accept_encoding_t * header, const char * hvalue)
Parse a Accept-Encoding element.
Parameters
header The element to work on.
hvalue The string to parse.
References osip_accept_encoding::element, and osip_accept_encoding::gen_params.
Referenced by osip_message_set_accept_encoding().
void osip_accept_encoding_set_element (osip_accept_encoding_t * header, char * value)
Set the value of an Accept-Encoding element.
Parameters
header The element to work on.
value The token value to set.
References osip_accept_encoding::element.
int osip_accept_encoding_to_str (const osip_accept_encoding_t * header, char ** dest)
Get a string representation of a Accept-Encoding element.
Parameters
header The element to work on.
dest A pointer on the new allocated string.
References osip_accept_encoding::element, osip_accept_encoding::gen_params, osip_uri_param::gname, osip_uri_param::gvalue, osip_list_eol(), and osip_list_get().