libosip: oSIP SDP parser Handling
oSIP SDP parser Handling
Classes
struct sdp_bandwidth
struct sdp_time_descr
struct sdp_key
struct sdp_attribute
struct sdp_connection
struct sdp_media
struct sdp_message
Macros
#define sdp_e_email_get sdp_message_e_email_get
Typedefs
typedef struct sdp_bandwidth sdp_bandwidth_t
typedef struct sdp_time_descr sdp_time_descr_t
typedef struct sdp_key sdp_key_t
typedef struct sdp_attribute sdp_attribute_t
typedef struct sdp_connection sdp_connection_t
typedef struct sdp_media sdp_media_t
typedef struct sdp_message sdp_message_t
Functions
int sdp_bandwidth_init (sdp_bandwidth_t **elem)
void sdp_bandwidth_free (sdp_bandwidth_t *elem)
int sdp_time_descr_init (sdp_time_descr_t **elem)
void sdp_time_descr_free (sdp_time_descr_t *elem)
int sdp_key_init (sdp_key_t **elem)
void sdp_key_free (sdp_key_t *elem)
int sdp_attribute_init (sdp_attribute_t **elem)
void sdp_attribute_free (sdp_attribute_t *elem)
int sdp_connection_init (sdp_connection_t **elem)
void sdp_connection_free (sdp_connection_t *elem)
int sdp_media_init (sdp_media_t **elem)
void sdp_media_free (sdp_media_t *elem)
int sdp_message_init (sdp_message_t **sdp)
int sdp_message_parse (sdp_message_t *sdp, const char *buf)
int sdp_message_to_str (sdp_message_t *sdp, char **dest)
void sdp_message_free (sdp_message_t *sdp)
int sdp_message_clone (sdp_message_t *sdp, sdp_message_t **dest)
int sdp_message_v_version_set (sdp_message_t *sdp, char *value)
char * sdp_message_v_version_get (sdp_message_t *sdp)
int sdp_message_o_origin_set (sdp_message_t *sdp, char *username, char *sess_id, char *sess_version, char *nettype, char *addrtype, char *addr)
char * sdp_message_o_username_get (sdp_message_t *sdp)
char * sdp_message_o_sess_id_get (sdp_message_t *sdp)
char * sdp_message_o_sess_version_get (sdp_message_t *sdp)
char * sdp_message_o_nettype_get (sdp_message_t *sdp)
char * sdp_message_o_addrtype_get (sdp_message_t *sdp)
char * sdp_message_o_addr_get (sdp_message_t *sdp)
int sdp_message_s_name_set (sdp_message_t *sdp, char *value)
char * sdp_message_s_name_get (sdp_message_t *sdp)
int sdp_message_i_info_set (sdp_message_t *sdp, int pos_media, char *value)
char * sdp_message_i_info_get (sdp_message_t *sdp, int pos_media)
int sdp_message_u_uri_set (sdp_message_t *sdp, char *value)
char * sdp_message_u_uri_get (sdp_message_t *sdp)
int sdp_message_e_email_add (sdp_message_t *sdp, char *value)
char * sdp_message_e_email_get (sdp_message_t *sdp, int pos)
int sdp_message_p_phone_add (sdp_message_t *sdp, char *value)
char * sdp_message_p_phone_get (sdp_message_t *sdp, int pos)
int sdp_message_c_connection_add (sdp_message_t *sdp, int pos_media, char *nettype, char *addrtype, char *addr, char *addr_multicast_ttl, char *addr_multicast_int)
char * sdp_message_c_nettype_get (sdp_message_t *sdp, int pos_media, int pos)
char * sdp_message_c_addrtype_get (sdp_message_t *sdp, int pos_media, int pos)
char * sdp_message_c_addr_get (sdp_message_t *sdp, int pos_media, int pos)
char * sdp_message_c_addr_multicast_ttl_get (sdp_message_t *sdp, int pos_media, int pos)
char * sdp_message_c_addr_multicast_int_get (sdp_message_t *sdp, int pos_media, int pos)
int sdp_message_b_bandwidth_add (sdp_message_t *sdp, int pos_media, char *bwtype, char *bandwidth)
sdp_bandwidth_t * sdp_message_bandwidth_get (sdp_message_t *sdp, int pos_media, int pos)
char * sdp_message_b_bwtype_get (sdp_message_t *sdp, int pos_media, int pos)
char * sdp_message_b_bandwidth_get (sdp_message_t *sdp, int pos_media, int pos)
int sdp_message_t_time_descr_add (sdp_message_t *sdp, char *start, char *stop)
char * sdp_message_t_start_time_get (sdp_message_t *sdp, int pos_td)
char * sdp_message_t_stop_time_get (sdp_message_t *sdp, int pos_td)
int sdp_message_r_repeat_add (sdp_message_t *sdp, int pos_time_descr, char *value)
char * sdp_message_r_repeat_get (sdp_message_t *sdp, int pos_time_descr, int pos_repeat)
int sdp_message_z_adjustments_set (sdp_message_t *sdp, char *value)
char * sdp_message_z_adjustments_get (sdp_message_t *sdp)
int sdp_message_k_key_set (sdp_message_t *sdp, int pos_media, char *keytype, char *keydata)
char * sdp_message_k_keytype_get (sdp_message_t *sdp, int pos_media)
char * sdp_message_k_keydata_get (sdp_message_t *sdp, int pos_media)
int sdp_message_a_attribute_add (sdp_message_t *sdp, int pos_media, char *att_field, char *att_value)
int sdp_message_a_attribute_del (sdp_message_t *sdp, int pos_media, char *att_field)
int sdp_message_a_attribute_del_at_index (sdp_message_t *sdp, int pos_media, char *att_field, int pos_attr)
sdp_attribute_t * sdp_message_attribute_get (sdp_message_t *sdp, int pos_media, int pos)
char * sdp_message_a_att_field_get (sdp_message_t *sdp, int pos_media, int pos)
char * sdp_message_a_att_value_get (sdp_message_t *sdp, int pos_media, int pos)
int sdp_message_endof_media (sdp_message_t *sdp, int pos)
int sdp_message_m_media_add (sdp_message_t *sdp, char *media, char *port, char *number_of_port, char *proto)
char * sdp_message_m_media_get (sdp_message_t *sdp, int pos_media)
char * sdp_message_m_port_get (sdp_message_t *sdp, int pos_media)
int sdp_message_m_port_set (sdp_message_t *sdp, int pos_media, char *port)
char * sdp_message_m_number_of_port_get (sdp_message_t *sdp, int pos_media)
char * sdp_message_m_proto_get (sdp_message_t *sdp, int pos_media)
int sdp_message_m_payload_add (sdp_message_t *sdp, int pos_media, char *payload)
char * sdp_message_m_payload_get (sdp_message_t *sdp, int pos_media, int pos)
int sdp_message_m_payload_del (sdp_message_t *sdp, int pos_media, int pos)
Detailed Description
Macro Definition Documentation
#define sdp_e_email_get sdp_message_e_email_get
OBSOLETE: see sdp_message_e_email_get
Typedef Documentation
sdp_attribute_t
Structure for referencing an attribute header.
sdp_bandwidth_t
Structure for referencing bandwidth header.
sdp_connection_t
Structure for referencing a connection header.
sdp_key_t
Structure for referencing key header.
sdp_media_t
Structure for referencing a media header.
sdp_message_t
Structure for referencing a SDP packet.
sdp_time_descr_t
Structure for referencing time description header.
Function Documentation
void sdp_attribute_free (sdp_attribute_t * elem)
Free a attribute element.
Parameters
elem The element to work on.
References sdp_attribute::a_att_field, and sdp_attribute::a_att_value.
Referenced by sdp_media_free(), sdp_message_a_attribute_del(), sdp_message_a_attribute_del_at_index(), sdp_message_free(), and sdp_message_init().
int sdp_attribute_init (sdp_attribute_t ** elem)
Allocate an attribute element.
Parameters
elem The element to work on.
Referenced by sdp_message_a_attribute_add().
void sdp_bandwidth_free (sdp_bandwidth_t * elem)
Free a bandwidth element.
Parameters
elem The element to work on.
References sdp_bandwidth::b_bandwidth, and sdp_bandwidth::b_bwtype.
Referenced by sdp_media_free(), sdp_media_init(), sdp_message_free(), and sdp_message_init().
int sdp_bandwidth_init (sdp_bandwidth_t ** elem)
Allocate a bandwidth element.
Parameters
elem The element to work on.
Referenced by sdp_message_b_bandwidth_add().
void sdp_connection_free (sdp_connection_t * elem)
Free a connection element.
Parameters
elem The element to work on.
References sdp_connection::c_addr, sdp_connection::c_addr_multicast_int, sdp_connection::c_addr_multicast_ttl, sdp_connection::c_addrtype, and sdp_connection::c_nettype.
Referenced by sdp_media_free(), sdp_media_init(), and sdp_message_free().
int sdp_connection_init (sdp_connection_t ** elem)
Allocate a connection element.
Parameters
elem The element to work on.
Referenced by sdp_message_c_connection_add().
void sdp_key_free (sdp_key_t * elem)
Free a key element.
Parameters
elem The element to work on.
References sdp_key::k_keydata, and sdp_key::k_keytype.
Referenced by sdp_media_free(), and sdp_message_free().
int sdp_key_init (sdp_key_t ** elem)
Allocate a key element.
Parameters
elem The element to work on.
Referenced by sdp_message_k_key_set().
void sdp_media_free (sdp_media_t * elem)
Free a media element.
Parameters
elem The element to work on.
References sdp_media::a_attributes, sdp_media::b_bandwidths, sdp_media::c_connections, sdp_media::i_info, sdp_media::k_key, sdp_media::m_media, sdp_media::m_number_of_port, sdp_media::m_payloads, sdp_media::m_port, sdp_media::m_proto, osip_list_ofchar_free(), osip_list_special_free(), sdp_attribute_free(), sdp_bandwidth_free(), sdp_connection_free(), and sdp_key_free().
Referenced by sdp_message_free().
int sdp_media_init (sdp_media_t ** elem)
Allocate a media element.
Parameters
elem The element to work on.
References osip_list_init(), osip_list_ofchar_free(), osip_list_special_free(), sdp_bandwidth_free(), and sdp_connection_free().
Referenced by sdp_message_m_media_add().
char* sdp_message_a_att_field_get (sdp_message_t * sdp, int pos_media, int pos)
Get the attribute name ('a' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
pos The attribute line number.
References sdp_attribute::a_att_field, and sdp_message_attribute_get().
char* sdp_message_a_att_value_get (sdp_message_t * sdp, int pos_media, int pos)
Get the attribute value ('a' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
pos The attribute line number.
References sdp_attribute::a_att_value, and sdp_message_attribute_get().
int sdp_message_a_attribute_add (sdp_message_t * sdp, int pos_media, char * att_field, char * att_value)
Set the version in a SDP packet.
Parameters
sdp The element to work on.
pos_media The line number.
att_field The token value.
att_value The token value.
References sdp_attribute::a_att_field, sdp_attribute::a_att_value, sdp_media::a_attributes, sdp_message::a_attributes, sdp_message::m_medias, osip_list_add(), osip_list_get(), osip_list_size(), and sdp_attribute_init().
int sdp_message_a_attribute_del (sdp_message_t * sdp, int pos_media, char * att_field)
delete all attribute fields specified by att_field.
Parameters
sdp The element to work on.
pos_media The line number.
att_field The value to remove.
References sdp_attribute::a_att_field, sdp_media::a_attributes, sdp_message::a_attributes, sdp_message::m_medias, osip_list_get(), osip_list_remove(), osip_list_size(), and sdp_attribute_free().
int sdp_message_a_attribute_del_at_index (sdp_message_t * sdp, int pos_media, char * att_field, int pos_attr)
delete one specific attribute fields specified by att_field.
Parameters
sdp The element to work on.
pos_media The line number.
att_field The value to remove.
pos_attr The index of attribute to remove.
References sdp_attribute::a_att_field, sdp_media::a_attributes, sdp_message::a_attributes, sdp_message::m_medias, osip_list_get(), osip_list_remove(), osip_list_size(), and sdp_attribute_free().
sdp_attribute_t* sdp_message_attribute_get (sdp_message_t * sdp, int pos_media, int pos)
Get one of the attribute ('a' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
pos The attribute line number.
References sdp_media::a_attributes, sdp_message::a_attributes, sdp_message::m_medias, and osip_list_get().
Referenced by sdp_message_a_att_field_get(), and sdp_message_a_att_value_get().
int sdp_message_b_bandwidth_add (sdp_message_t * sdp, int pos_media, char * bwtype, char * bandwidth)
Set the version in a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
bwtype The token value.
bandwidth The token value.
References sdp_bandwidth::b_bandwidth, sdp_media::b_bandwidths, sdp_message::b_bandwidths, sdp_bandwidth::b_bwtype, sdp_message::m_medias, osip_list_add(), osip_list_get(), osip_list_size(), and sdp_bandwidth_init().
char* sdp_message_b_bandwidth_get (sdp_message_t * sdp, int pos_media, int pos)
Get the bandwidth value ('b' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
pos The index in the bandwidth element list..
References sdp_bandwidth::b_bandwidth, and sdp_message_bandwidth_get().
char* sdp_message_b_bwtype_get (sdp_message_t * sdp, int pos_media, int pos)
Get the bandwidth type ('b' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
pos The index in the bandwidth element list..
References sdp_bandwidth::b_bwtype, and sdp_message_bandwidth_get().
sdp_bandwidth_t* sdp_message_bandwidth_get (sdp_message_t * sdp, int pos_media, int pos)
Get the bandwidth ('b' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
pos The index in the bandwidth element list..
References sdp_media::b_bandwidths, sdp_message::b_bandwidths, sdp_message::m_medias, and osip_list_get().
Referenced by sdp_message_b_bandwidth_get(), and sdp_message_b_bwtype_get().
char* sdp_message_c_addr_get (sdp_message_t * sdp, int pos_media, int pos)
Get the address ('c' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
pos The index in the connection element list..
References sdp_connection::c_addr.
char* sdp_message_c_addr_multicast_int_get (sdp_message_t * sdp, int pos_media, int pos)
Get the multicast int info ('c' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
pos The index in the connection element list..
References sdp_connection::c_addr_multicast_int.
char* sdp_message_c_addr_multicast_ttl_get (sdp_message_t * sdp, int pos_media, int pos)
Get the multicast ttl ('c' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
pos The index in the connection element list..
References sdp_connection::c_addr_multicast_ttl.
char* sdp_message_c_addrtype_get (sdp_message_t * sdp, int pos_media, int pos)
Get the address type ('c' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
pos The index in the connection element list..
References sdp_connection::c_addrtype.
int sdp_message_c_connection_add (sdp_message_t * sdp, int pos_media, char * nettype, char * addrtype, char * addr, char * addr_multicast_ttl, char * addr_multicast_int)
Set the version in a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
nettype The token value.
addrtype The token value.
addr The token value.
addr_multicast_ttl The token value.
addr_multicast_int The token value.
References sdp_connection::c_addr, sdp_connection::c_addr_multicast_int, sdp_connection::c_addr_multicast_ttl, sdp_connection::c_addrtype, sdp_message::c_connection, sdp_media::c_connections, sdp_connection::c_nettype, sdp_message::m_medias, osip_list_add(), osip_list_get(), osip_list_size(), and sdp_connection_init().
char* sdp_message_c_nettype_get (sdp_message_t * sdp, int pos_media, int pos)
Get the network type ('c' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
pos The index in the connection element list..
References sdp_connection::c_nettype.
int sdp_message_clone (sdp_message_t * sdp, sdp_message_t ** dest)
Clone a SDP packet.
Parameters
sdp The element to work on.
dest The cloned element.
References sdp_message_free(), sdp_message_init(), sdp_message_parse(), and sdp_message_to_str().
int sdp_message_e_email_add (sdp_message_t * sdp, char * value)
Set the version in a SDP packet.
Parameters
sdp The element to work on.
value The token value.
References sdp_message::e_emails, and osip_list_add().
char* sdp_message_e_email_get (sdp_message_t * sdp, int pos)
Get one of the email ('e' field) of a SDP packet.
Parameters
sdp The element to work on.
pos the index of the email line.
References sdp_message::e_emails, osip_list_get(), and osip_list_size().
int sdp_message_endof_media (sdp_message_t * sdp, int pos)
Check if there is more media lines a SDP packet.
Parameters
sdp The element to work on.
pos The attribute line number.
References sdp_message::m_medias, and osip_list_eol().
void sdp_message_free (sdp_message_t * sdp)
Free a SDP packet.
Parameters
sdp The element to work on.
References sdp_message::a_attributes, sdp_message::b_bandwidths, sdp_message::c_connection, sdp_message::e_emails, sdp_message::i_info, sdp_message::k_key, sdp_message::m_medias, sdp_message::o_addr, sdp_message::o_addrtype, sdp_message::o_nettype, sdp_message::o_sess_id, sdp_message::o_sess_version, sdp_message::o_username, osip_list_ofchar_free(), osip_list_special_free(), sdp_message::p_phones, sdp_message::s_name, sdp_attribute_free(), sdp_bandwidth_free(), sdp_connection_free(), sdp_key_free(), sdp_media_free(), sdp_time_descr_free(), sdp_message::t_descrs, sdp_message::u_uri, sdp_message::v_version, and sdp_message::z_adjustments.
Referenced by sdp_message_clone().
char* sdp_message_i_info_get (sdp_message_t * sdp, int pos_media)
Get the session info ('i' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
References sdp_media::i_info, sdp_message::i_info, sdp_message::m_medias, and osip_list_get().
int sdp_message_i_info_set (sdp_message_t * sdp, int pos_media, char * value)
Set the version in a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
value The token value.
References sdp_media::i_info, sdp_message::i_info, sdp_message::m_medias, and osip_list_get().
int sdp_message_init (sdp_message_t ** sdp)
Allocate a SDP packet.
Parameters
sdp The element to work on.
References osip_list_init(), osip_list_ofchar_free(), osip_list_special_free(), sdp_attribute_free(), sdp_bandwidth_free(), and sdp_time_descr_free().
Referenced by sdp_message_clone().
int sdp_message_k_key_set (sdp_message_t * sdp, int pos_media, char * keytype, char * keydata)
Add a key in a SDP packet.
Parameters
sdp The element to work on.
pos_media index of m field.
keytype The token value.
keydata The token value.
References sdp_media::k_key, sdp_message::k_key, sdp_key::k_keydata, sdp_key::k_keytype, sdp_message::m_medias, osip_list_get(), osip_list_size(), and sdp_key_init().
char* sdp_message_k_keydata_get (sdp_message_t * sdp, int pos_media)
Get the key value ('k' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
References sdp_media::k_key, sdp_message::k_key, sdp_key::k_keydata, sdp_message::m_medias, osip_list_get(), and osip_list_size().
char* sdp_message_k_keytype_get (sdp_message_t * sdp, int pos_media)
Get the key type ('k' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The media line number.
References sdp_media::k_key, sdp_message::k_key, sdp_key::k_keytype, sdp_message::m_medias, osip_list_get(), and osip_list_size().
int sdp_message_m_media_add (sdp_message_t * sdp, char * media, char * port, char * number_of_port, char * proto)
Add a media line in a SDP packet.
Parameters
sdp The element to work on.
media The token value.
port The token value.
number_of_port The token value.
proto The token value.
References sdp_media::m_media, sdp_message::m_medias, sdp_media::m_number_of_port, sdp_media::m_port, sdp_media::m_proto, osip_list_add(), and sdp_media_init().
char* sdp_message_m_media_get (sdp_message_t * sdp, int pos_media)
Get the media type ('m' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The line number.
References sdp_media::m_media, sdp_message::m_medias, and osip_list_get().
char* sdp_message_m_number_of_port_get (sdp_message_t * sdp, int pos_media)
Get the number of port ('m' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The line number.
References sdp_message::m_medias, sdp_media::m_number_of_port, and osip_list_get().
int sdp_message_m_payload_add (sdp_message_t * sdp, int pos_media, char * payload)
Set the payload in a SDP packet.
Parameters
sdp The element to work on.
pos_media The line number.
payload The token value.
References sdp_message::m_medias, sdp_media::m_payloads, osip_list_add(), and osip_list_get().
int sdp_message_m_payload_del (sdp_message_t * sdp, int pos_media, int pos)
Remove a payload in a SDP packet.
Parameters
sdp The element to work on.
pos_media The line number.
pos The position of the payload in the media line.
References sdp_message::m_medias, sdp_media::m_payloads, osip_list_get(), and osip_list_remove().
char* sdp_message_m_payload_get (sdp_message_t * sdp, int pos_media, int pos)
Get one of the payload number ('m' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The line number.
pos The i th payload element.
References sdp_message::m_medias, sdp_media::m_payloads, and osip_list_get().
char* sdp_message_m_port_get (sdp_message_t * sdp, int pos_media)
Get the port number ('m' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The line number.
References sdp_message::m_medias, sdp_media::m_port, and osip_list_get().
int sdp_message_m_port_set (sdp_message_t * sdp, int pos_media, char * port)
Set the port number ('m' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The line number.
port The new port to set (must be allocated with osip_malloc)
References sdp_message::m_medias, sdp_media::m_port, and osip_list_get().
char* sdp_message_m_proto_get (sdp_message_t * sdp, int pos_media)
Get the protocol ('m' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_media The line number.
References sdp_message::m_medias, sdp_media::m_proto, and osip_list_get().
char* sdp_message_o_addr_get (sdp_message_t * sdp)
Get the addr ('o' field) of a SDP packet.
Parameters
sdp The element to work on.
References sdp_message::o_addr.
char* sdp_message_o_addrtype_get (sdp_message_t * sdp)
Get the addrtype ('o' field) of a SDP packet.
Parameters
sdp The element to work on.
References sdp_message::o_addrtype.
char* sdp_message_o_nettype_get (sdp_message_t * sdp)
Get the nettype ('o' field) of a SDP packet.
Parameters
sdp The element to work on.
References sdp_message::o_nettype.
int sdp_message_o_origin_set (sdp_message_t * sdp, char * username, char * sess_id, char * sess_version, char * nettype, char * addrtype, char * addr)
Set the origin field in a SDP packet.
Parameters
sdp The element to work on.
username The token value.
sess_id The token value.
sess_version The token value.
nettype The token value.
addrtype The token value.
addr The token value.
References sdp_message::o_addr, sdp_message::o_addrtype, sdp_message::o_nettype, sdp_message::o_sess_id, sdp_message::o_sess_version, and sdp_message::o_username.
char* sdp_message_o_sess_id_get (sdp_message_t * sdp)
Get the session id ('o' field) of a SDP packet.
Parameters
sdp The element to work on.
References sdp_message::o_sess_id.
char* sdp_message_o_sess_version_get (sdp_message_t * sdp)
Get the session version ('o' field) of a SDP packet.
Parameters
sdp The element to work on.
References sdp_message::o_sess_version.
char* sdp_message_o_username_get (sdp_message_t * sdp)
Get the username ('o' field) of a SDP packet.
Parameters
sdp The element to work on.
References sdp_message::o_username.
int sdp_message_p_phone_add (sdp_message_t * sdp, char * value)
Set the version in a SDP packet.
Parameters
sdp The element to work on.
value The token value.
References osip_list_add(), and sdp_message::p_phones.
char* sdp_message_p_phone_get (sdp_message_t * sdp, int pos)
Get one of the phone ('p' field) of a SDP packet.
Parameters
sdp The element to work on.
pos the index of the phone line.
References osip_list_get(), osip_list_size(), and sdp_message::p_phones.
int sdp_message_parse (sdp_message_t * sdp, const char * buf)
Parse a SDP packet.
Parameters
sdp The element to work on.
buf The buffer to parse.
References sdp_message::e_emails, osip_list_size(), and sdp_message::p_phones.
Referenced by sdp_message_clone().
int sdp_message_r_repeat_add (sdp_message_t * sdp, int pos_time_descr, char * value)
Set the repeat information ('r' field) in a SDP packet.
Parameters
sdp The element to work on.
pos_time_descr index of t field.
value The token value.
References osip_list_add(), osip_list_get(), sdp_time_descr::r_repeats, and sdp_message::t_descrs.
char* sdp_message_r_repeat_get (sdp_message_t * sdp, int pos_time_descr, int pos_repeat)
Get the repeat information ('r' field) in a SDP packet.
Parameters
sdp The element to work on.
pos_time_descr index of t field.
pos_repeat index of element in the 'r' field.
References osip_list_get(), sdp_time_descr::r_repeats, and sdp_message::t_descrs.
char* sdp_message_s_name_get (sdp_message_t * sdp)
Get the session name ('s' field) of a SDP packet.
Parameters
sdp The element to work on.
References sdp_message::s_name.
int sdp_message_s_name_set (sdp_message_t * sdp, char * value)
Set the session name in a SDP packet.
Parameters
sdp The element to work on.
value The token value.
References sdp_message::s_name.
char* sdp_message_t_start_time_get (sdp_message_t * sdp, int pos_td)
Get the start time value ('t' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_td The time description line number.
References osip_list_get(), sdp_message::t_descrs, and sdp_time_descr::t_start_time.
char* sdp_message_t_stop_time_get (sdp_message_t * sdp, int pos_td)
Get the stop time value ('t' field) of a SDP packet.
Parameters
sdp The element to work on.
pos_td The time description line number.
References osip_list_get(), sdp_message::t_descrs, and sdp_time_descr::t_stop_time.
int sdp_message_t_time_descr_add (sdp_message_t * sdp, char * start, char * stop)
Set the version in a SDP packet.
Parameters
sdp The element to work on.
start The token value.
stop The token value.
References osip_list_add(), sdp_time_descr_init(), sdp_message::t_descrs, sdp_time_descr::t_start_time, and sdp_time_descr::t_stop_time.
int sdp_message_to_str (sdp_message_t * sdp, char ** dest)
Get a string representation of a SDP packet.
Parameters
sdp The element to work on.
dest The resulting new allocated buffer.
References sdp_message::a_attributes, sdp_message::b_bandwidths, BODY_MESSAGE_MAX_SIZE, sdp_message::c_connection, sdp_message::e_emails, sdp_message::i_info, sdp_message::k_key, sdp_message::m_medias, sdp_message::o_addr, sdp_message::o_addrtype, sdp_message::o_nettype, sdp_message::o_sess_id, sdp_message::o_sess_version, sdp_message::o_username, osip_list_eol(), osip_list_get(), sdp_message::p_phones, sdp_message::s_name, sdp_message::t_descrs, sdp_message::u_uri, sdp_message::v_version, and sdp_message::z_adjustments.
Referenced by sdp_message_clone().
char* sdp_message_u_uri_get (sdp_message_t * sdp)
Get the uri ('u' field) of a SDP packet.
Parameters
sdp The element to work on.
References sdp_message::u_uri.
int sdp_message_u_uri_set (sdp_message_t * sdp, char * value)
Set the session info in a SDP packet.
Parameters
sdp The element to work on.
value The token value.
References sdp_message::u_uri.
char* sdp_message_v_version_get (sdp_message_t * sdp)
Get the version ('v' field) of a SDP packet.
Parameters
sdp The element to work on.
References sdp_message::v_version.
int sdp_message_v_version_set (sdp_message_t * sdp, char * value)
Set the version in a SDP packet.
Parameters
sdp The element to work on.
value The token value.
References sdp_message::v_version.
char* sdp_message_z_adjustments_get (sdp_message_t * sdp)
Get the adjustments ('z' field) of a SDP packet.
Parameters
sdp The element to work on.
References sdp_message::z_adjustments.
int sdp_message_z_adjustments_set (sdp_message_t * sdp, char * value)
Set the adjustments ('z' field) of a SDP packet.
Parameters
sdp The element to work on.
value The token value.
References sdp_message::z_adjustments.
void sdp_time_descr_free (sdp_time_descr_t * elem)
Free a time description element.
Parameters
elem The element to work on.
References osip_list_ofchar_free(), sdp_time_descr::r_repeats, sdp_time_descr::t_start_time, and sdp_time_descr::t_stop_time.
Referenced by sdp_message_free(), and sdp_message_init().
int sdp_time_descr_init (sdp_time_descr_t ** elem)
Allocate a time description element.
Parameters
elem The element to work on.
References osip_list_init().
Referenced by sdp_message_t_time_descr_add().