libosip: oSIP call-info header definition.
oSIP call-info header definition.
oSIP headers definitions
Classes
struct osip_call_info
Typedefs
typedef struct osip_call_info osip_call_info_t
Functions
int osip_call_info_init (osip_call_info_t **header)
void osip_call_info_free (osip_call_info_t *header)
int osip_call_info_parse (osip_call_info_t *header, const char *hvalue)
int osip_call_info_to_str (const osip_call_info_t *header, char **dest)
int osip_call_info_clone (const osip_call_info_t *header, osip_call_info_t **dest)
char * osip_call_info_get_uri (osip_call_info_t *header)
void osip_call_info_set_uri (osip_call_info_t *header, char *uri)
Detailed Description
Typedef Documentation
osip_call_info_t
Structure for Call-Info headers.
Function Documentation
int osip_call_info_clone (const osip_call_info_t * header, osip_call_info_t ** dest)
Clone a Call-Info element.
Parameters
header The element to work on.
dest A pointer on the copy of the element.
References osip_call_info::element, osip_call_info::gen_params, osip_call_info_free(), osip_call_info_init(), osip_generic_param_clone, and osip_list_clone().
Referenced by osip_message_clone().
void osip_call_info_free (osip_call_info_t * header)
Free a Call-Info element.
Parameters
header The element to work on.
References osip_call_info::element, and osip_call_info::gen_params.
Referenced by osip_call_info_clone(), osip_message_free(), and osip_message_set_call_info().
char* osip_call_info_get_uri (osip_call_info_t * header)
Get the uri from a Call_Info header.
Parameters
header The element to work on.
References osip_call_info::element.
int osip_call_info_init (osip_call_info_t ** header)
Allocate a Call-Info element.
Parameters
header The element to work on.
References osip_list_init().
Referenced by osip_call_info_clone(), and osip_message_set_call_info().
int osip_call_info_parse (osip_call_info_t * header, const char * hvalue)
Parse a Call-Info element.
Parameters
header The element to work on.
hvalue The string to parse.
References osip_call_info::element, and osip_call_info::gen_params.
Referenced by osip_message_set_call_info().
void osip_call_info_set_uri (osip_call_info_t * header, char * uri)
Set the uri in the Call_Info element.
Parameters
header The element to work on.
uri The value of the element.
References osip_call_info::element.
int osip_call_info_to_str (const osip_call_info_t * header, char ** dest)
Get a string representation of a Call-Info element.
Parameters
header The element to work on.
dest A pointer on the new allocated string.
References osip_call_info::element, osip_call_info::gen_params, osip_uri_param::gname, osip_uri_param::gvalue, osip_list_eol(), and osip_list_get().