libosip: oSIP call-id header definition.
oSIP call-id header definition.
oSIP headers definitions
Classes
struct osip_call_id
Typedefs
typedef struct osip_call_id osip_call_id_t
Functions
int osip_call_id_init (osip_call_id_t **header)
void osip_call_id_free (osip_call_id_t *header)
int osip_call_id_parse (osip_call_id_t *header, const char *hvalue)
int osip_call_id_to_str (const osip_call_id_t *header, char **dest)
int osip_call_id_clone (const osip_call_id_t *header, osip_call_id_t **dest)
void osip_call_id_set_number (osip_call_id_t *header, char *value)
char * osip_call_id_get_number (osip_call_id_t *header)
void osip_call_id_set_host (osip_call_id_t *header, char *value)
char * osip_call_id_get_host (osip_call_id_t *header)
int osip_call_id_match (osip_call_id_t *callid1, osip_call_id_t *callid2)
Detailed Description
Typedef Documentation
osip_call_id_t
Structure for Call-Id headers.
Function Documentation
int osip_call_id_clone (const osip_call_id_t * header, osip_call_id_t ** dest)
Clone a Call-id element.
Parameters
header The element to work on.
dest A pointer on the copy of the element.
References osip_call_id::host, osip_call_id::number, and osip_call_id_init().
Referenced by osip_message_clone().
void osip_call_id_free (osip_call_id_t * header)
Free a Call-id element.
Parameters
header The element to work on.
References osip_call_id::host, and osip_call_id::number.
Referenced by osip_message_free(), osip_message_set_call_id(), and osip_transaction_free2().
char* osip_call_id_get_host (osip_call_id_t * header)
Get the host from a Call-Id header.
Parameters
header The element to work on.
References osip_call_id::host.
char* osip_call_id_get_number (osip_call_id_t * header)
Get the number from a Call-Id header.
Parameters
header The element to work on.
References osip_call_id::number.
int osip_call_id_init (osip_call_id_t ** header)
Allocate a Call-id element.
Parameters
header The element to work on.
Referenced by osip_call_id_clone(), and osip_message_set_call_id().
int osip_call_id_match (osip_call_id_t * callid1, osip_call_id_t * callid2)
Check if the Call-Id headers match. NOTE: THIS IS AN INTERNAL METHOD ONLY
Parameters
callid1 The initial Call-Id header.
callid2 The new Call-Id header.
References osip_call_id::host, and osip_call_id::number.
int osip_call_id_parse (osip_call_id_t * header, const char * hvalue)
Parse a Call-id element.
Parameters
header The element to work on.
hvalue The string to parse.
References osip_call_id::host, and osip_call_id::number.
Referenced by osip_message_set_call_id().
void osip_call_id_set_host (osip_call_id_t * header, char * value)
Set the host in the Call-Id element.
Parameters
header The element to work on.
value The value of the element.
References osip_call_id::host.
void osip_call_id_set_number (osip_call_id_t * header, char * value)
Set the number in the Call-Id element.
Parameters
header The element to work on.
value The value of the element.
References osip_call_id::number.
int osip_call_id_to_str (const osip_call_id_t * header, char ** dest)
Get a string representation of a Call-id element.
Parameters
header The element to work on.
dest A pointer on the new allocated string.
References osip_call_id::host, and osip_call_id::number.
Referenced by osip_dialog_match_as_uac(), and osip_dialog_match_as_uas().