libosip: oSIP authentication-info header definition.
oSIP authentication-info header definition.
oSIP headers definitions
Classes
struct osip_authentication_info
Typedefs
typedef struct
osip_authentication_info osip_authentication_info_t
Functions
int osip_authentication_info_init (osip_authentication_info_t **header)
int osip_authentication_info_parse (osip_authentication_info_t *header, const char *hvalue)
int osip_authentication_info_to_str (const osip_authentication_info_t *header, char **dest)
void osip_authentication_info_free (osip_authentication_info_t *header)
int osip_authentication_info_clone (const osip_authentication_info_t *header, osip_authentication_info_t **dest)
char * osip_authentication_info_get_nextnonce (osip_authentication_info_t *header)
void osip_authentication_info_set_nextnonce (osip_authentication_info_t *header, char *value)
char * osip_authentication_info_get_cnonce (osip_authentication_info_t *header)
void osip_authentication_info_set_cnonce (osip_authentication_info_t *header, char *value)
char * osip_authentication_info_get_qop_options (osip_authentication_info_t *header)
void osip_authentication_info_set_qop_options (osip_authentication_info_t *header, char *value)
char * osip_authentication_info_get_rspauth (osip_authentication_info_t *header)
void osip_authentication_info_set_rspauth (osip_authentication_info_t *header, char *value)
char * osip_authentication_info_get_nonce_count (osip_authentication_info_t *header)
void osip_authentication_info_set_nonce_count (osip_authentication_info_t *header, char *value)
Detailed Description
Typedef Documentation
osip_authentication_info_t
Structure for Authentication-Info headers.
Function Documentation
int osip_authentication_info_clone (const osip_authentication_info_t * header, osip_authentication_info_t ** dest)
Clone a Authenication-Info element.
Parameters
header The element to work on.
dest A pointer on the copy of the element.
References osip_authentication_info::cnonce, osip_authentication_info::nextnonce, osip_authentication_info::nonce_count, osip_authentication_info_init(), osip_authentication_info::qop_options, and osip_authentication_info::rspauth.
Referenced by osip_message_clone().
void osip_authentication_info_free (osip_authentication_info_t * header)
Free a Authenication-Info element.
Parameters
header The element to work on.
References osip_authentication_info::cnonce, osip_authentication_info::nextnonce, osip_authentication_info::nonce_count, osip_authentication_info::qop_options, and osip_authentication_info::rspauth.
Referenced by osip_message_free(), and osip_message_set_authentication_info().
char* osip_authentication_info_get_cnonce (osip_authentication_info_t * header)
Get value of the cnonce parameter from a Authenication-Info element.
Parameters
header The element to work on.
References osip_authentication_info::cnonce.
char* osip_authentication_info_get_nextnonce (osip_authentication_info_t * header)
Get value of the nextnonce parameter from a Authenication-Info element.
Parameters
header The element to work on.
References osip_authentication_info::nextnonce.
char* osip_authentication_info_get_nonce_count (osip_authentication_info_t * header)
Get value of the nc parameter from a Authenication-Info element.
Parameters
header The element to work on.
References osip_authentication_info::nonce_count.
char* osip_authentication_info_get_qop_options (osip_authentication_info_t * header)
Get value of the qop_options parameter from a Authenication-Info element.
Parameters
header The element to work on.
References osip_authentication_info::qop_options.
char* osip_authentication_info_get_rspauth (osip_authentication_info_t * header)
Get value of the rspauth parameter from a Authenication-Info element.
Parameters
header The element to work on.
References osip_authentication_info::rspauth.
int osip_authentication_info_init (osip_authentication_info_t ** header)
Allocate a Authenication-Info element.
Parameters
header The element to work on.
Referenced by osip_authentication_info_clone(), and osip_message_set_authentication_info().
int osip_authentication_info_parse (osip_authentication_info_t * header, const char * hvalue)
Parse a Authenication-Info element.
Parameters
header The element to work on.
hvalue The string to parse.
References osip_authentication_info::cnonce, osip_authentication_info::nextnonce, osip_authentication_info::nonce_count, osip_authentication_info::qop_options, and osip_authentication_info::rspauth.
Referenced by osip_message_set_authentication_info().
void osip_authentication_info_set_cnonce (osip_authentication_info_t * header, char * value)
Add the cnonce parameter from a Authenication-Info element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authentication_info::cnonce.
void osip_authentication_info_set_nextnonce (osip_authentication_info_t * header, char * value)
Add the nextnonce parameter from a Authenication-Info element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authentication_info::nextnonce.
void osip_authentication_info_set_nonce_count (osip_authentication_info_t * header, char * value)
Add the nc parameter from a Authenication-Info element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authentication_info::nonce_count.
void osip_authentication_info_set_qop_options (osip_authentication_info_t * header, char * value)
Add the qop_options parameter from a Authenication-Info element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authentication_info::qop_options.
void osip_authentication_info_set_rspauth (osip_authentication_info_t * header, char * value)
Add the rspauth parameter from a Authenication-Info element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authentication_info::rspauth.
int osip_authentication_info_to_str (const osip_authentication_info_t * header, char ** dest)
Get a string representation of a Authenication-Info element.
Parameters
header The element to work on.
dest A pointer on the new allocated string.
References osip_authentication_info::cnonce, osip_authentication_info::nextnonce, osip_authentication_info::nonce_count, osip_authentication_info::qop_options, and osip_authentication_info::rspauth.