libosip: oSIP accept header definition.
oSIP accept header definition.
oSIP headers definitions
Macros
#define accept_init(header) osip_content_type_init(header)
#define osip_accept_free osip_content_type_free
#define osip_accept_parse(header, hvalue) osip_content_type_parse(header, hvalue)
#define osip_accept_clone(header, dest) osip_content_type_clone(header, dest)
#define osip_accept_param_add(header, name, value) osip_generic_param_add((&(header)->gen_params),name,value)
#define osip_accept_param_get_byname(header, name, dest) osip_generic_param_get_byname((&(header)->gen_params),name,dest)
Typedefs
typedef osip_content_type_t osip_accept_t
Functions
int osip_accept_to_str (const osip_accept_t *header, char **dest)
Detailed Description
Macro Definition Documentation
#define accept_init (header) osip_content_type_init(header)
Allocate an Accept element.
Parameters
header The element to work on.
Referenced by osip_message_set_accept().
#define osip_accept_clone (header, dest) osip_content_type_clone(header, dest)
Clone an Accept element.
Parameters
header The element to work on.
dest A pointer on the copy of the element.
Referenced by osip_message_clone().
#define osip_accept_free osip_content_type_free
Free an Accept element.
Parameters
header The element to work on.
Referenced by osip_message_free(), and osip_message_set_accept().
#define osip_accept_param_add (header, name, value) osip_generic_param_add((&(header)->gen_params),name,value)
Allocate and add a header parameter in an Accept element.
Parameters
header The element to work on.
name The token name.
value The token value.
#define osip_accept_param_get_byname (header, name, dest) osip_generic_param_get_byname((&(header)->gen_params),name,dest)
Find a header parameter in an Accept element.
Parameters
header The element to work on.
name The token name to search.
dest A pointer on the element found.
#define osip_accept_parse (header, hvalue) osip_content_type_parse(header, hvalue)
Parse an Accept element.
Parameters
header The element to work on.
hvalue The string to parse.
Referenced by osip_message_set_accept().
Typedef Documentation
osip_accept_t
Structure for accept headers.
Function Documentation
int osip_accept_to_str (const osip_accept_t * header, char ** dest)
Get a string representation of an Accept element.
Parameters
header The element to work on.
dest A pointer on the new allocated string.
References osip_content_type::gen_params, osip_uri_param::gname, osip_uri_param::gvalue, osip_list_eol(), osip_list_get(), osip_list_size(), osip_content_type::subtype, and osip_content_type::type.