libosip: oSIP to header definition.
oSIP to header definition.
oSIP headers definitions
Macros
#define osip_to_set_displayname(header, value) osip_from_set_displayname((osip_from_t*)header,value)
#define osip_to_get_displayname(header) osip_from_get_displayname((osip_from_t*)header)
#define osip_to_set_url(header, url) osip_from_set_url((osip_from_t*)header,url)
#define osip_to_get_url(header) osip_from_get_url((osip_from_t*)header)
#define osip_to_param_get(header, pos, dest) osip_from_param_get((osip_from_t*)header,pos,dest)
#define osip_to_param_get_byname(header, name, dest) osip_generic_param_get_byname((&(header)->gen_params),name,dest)
#define osip_to_param_add(header, name, value) osip_generic_param_add((&(header)->gen_params),name,value)
#define osip_to_set_tag(header, value) osip_generic_param_add((&(header)->gen_params), osip_strdup("tag"),value)
#define osip_to_get_tag(header, dest) osip_generic_param_get_byname((&(header)->gen_params), "tag",dest)
Typedefs
typedef osip_from_t osip_to_t
Functions
int osip_to_init (osip_to_t **header)
void osip_to_free (osip_to_t *header)
int osip_to_parse (osip_to_t *header, const char *hvalue)
int osip_to_to_str (const osip_to_t *header, char **dest)
int osip_to_clone (const osip_to_t *header, osip_to_t **dest)
int osip_to_tag_match (osip_to_t *to1, osip_to_t *to2)
Detailed Description
Macro Definition Documentation
#define osip_to_get_displayname (header) osip_from_get_displayname((osip_from_t*)header)
Get the displayname from a To header.
Parameters
header The element to work on.
#define osip_to_get_tag (header, dest) osip_generic_param_get_byname((&(header)->gen_params), "tag",dest)
Find a tag parameter in a To element.
Parameters
header The element to work on.
dest A pointer on the element found.
Referenced by osip_dialog_match_as_uac(), and osip_dialog_update_tag_as_uac().
#define osip_to_get_url (header) osip_from_get_url((osip_from_t*)header)
Get the url from a To header.
Parameters
header The element to work on.
#define osip_to_param_add (header, name, value) osip_generic_param_add((&(header)->gen_params),name,value)
Allocate and add a generic parameter element in a list.
Parameters
header The element to work on.
name The token name.
value The token value.
#define osip_to_param_get (header, pos, dest) osip_from_param_get((osip_from_t*)header,pos,dest)
Get a header parameter from a To element.
Parameters
header The element to work on.
pos The index of the element to get.
dest A pointer on the element found.
#define osip_to_param_get_byname (header, name, dest) osip_generic_param_get_byname((&(header)->gen_params),name,dest)
Find a header parameter in a To element.
Parameters
header The element to work on.
name The token name to search.
dest A pointer on the element found.
#define osip_to_set_displayname (header, value) osip_from_set_displayname((osip_from_t*)header,value)
Set the displayname in the To element.
Parameters
header The element to work on.
value The value of the element.
#define osip_to_set_tag (header, value) osip_generic_param_add((&(header)->gen_params), osip_strdup("tag"),value)
Allocate and add a tag parameter element in a list.
Parameters
header The element to work on.
value The token value.
#define osip_to_set_url (header, url) osip_from_set_url((osip_from_t*)header,url)
Set the url in the To element.
Parameters
header The element to work on.
url The value of the element.
Typedef Documentation
osip_to_t
Structure for To headers.
Function Documentation
int osip_to_clone (const osip_to_t * header, osip_to_t ** dest)
Clone a To element.
Parameters
header The element to work on.
dest A pointer on the copy of the element.
References osip_from_clone().
Referenced by osip_message_clone().
void osip_to_free (osip_to_t * header)
Free a To element.
Parameters
header The element to work on.
References osip_from_free().
Referenced by osip_dialog_free(), osip_message_free(), osip_message_set_to(), and osip_transaction_free2().
int osip_to_init (osip_to_t ** header)
Allocate a To element.
Parameters
header The element to work on.
References osip_from_init().
Referenced by osip_message_set_to().
int osip_to_parse (osip_to_t * header, const char * hvalue)
Parse a To element.
Parameters
header The element to work on.
hvalue The string to parse.
References osip_from_parse().
Referenced by osip_message_set_to().
int osip_to_tag_match (osip_to_t * to1, osip_to_t * to2)
Check if the tags in the To headers match. NOTE: THIS IS AN INTERNAL METHOD ONLY
Parameters
to1 The first To header.
to2 The second To header.
References osip_from_tag_match().
int osip_to_to_str (const osip_to_t * header, char ** dest)
Get a string representation of a To element.
Parameters
header The element to work on.
dest A pointer on the new allocated string.
References osip_from_to_str().