libosip: oSIP contact header definition.
oSIP contact header definition.
oSIP headers definitions
Macros
#define osip_contact_get_displayname(header) osip_from_get_displayname((osip_from_t*)header)
#define osip_contact_set_displayname(header, value) osip_from_set_displayname((osip_from_t*)header, value)
#define osip_contact_get_url(header) osip_from_get_url((osip_from_t*)header)
#define osip_contact_set_url(header, url) osip_from_set_url((osip_from_t*)header,url)
#define osip_contact_param_get(header, pos, dest) osip_from_param_get((osip_from_t*)header,pos,dest)
#define osip_contact_param_add(header, name, value) osip_generic_param_add((&(header)->gen_params), name,value)
#define osip_contact_param_get_byname(header, name, dest) osip_generic_param_get_byname((&(header)->gen_params),name,dest)
Typedefs
typedef osip_from_t osip_contact_t
Functions
int osip_contact_init (osip_contact_t **header)
void osip_contact_free (osip_contact_t *header)
int osip_contact_parse (osip_contact_t *header, const char *hvalue)
int osip_contact_to_str (const osip_contact_t *header, char **dest)
int osip_contact_clone (const osip_contact_t *header, osip_contact_t **dest)
Detailed Description
Macro Definition Documentation
#define osip_contact_get_displayname (header) osip_from_get_displayname((osip_from_t*)header)
Get the displayname from a Contact header.
Parameters
header The element to work on.
#define osip_contact_get_url (header) osip_from_get_url((osip_from_t*)header)
Get the url from a Contact header.
Parameters
header The element to work on.
#define osip_contact_param_add (header, name, value) osip_generic_param_add((&(header)->gen_params), name,value)
Allocate and add a generic parameter element in a list.
Parameters
header The element to work on.
name The token name.
value The token value.
#define osip_contact_param_get (header, pos, dest) osip_from_param_get((osip_from_t*)header,pos,dest)
Get a header parameter from a Contact element.
Parameters
header The element to work on.
pos The index of the element to get.
dest A pointer on the element found.
#define osip_contact_param_get_byname (header, name, dest) osip_generic_param_get_byname((&(header)->gen_params),name,dest)
Find a header parameter in a Contact element.
Parameters
header The element to work on.
name The token name to search.
dest A pointer on the element found.
#define osip_contact_set_displayname (header, value) osip_from_set_displayname((osip_from_t*)header, value)
Set the displayname in the Contact element.
Parameters
header The element to work on.
value The value of the element.
#define osip_contact_set_url (header, url) osip_from_set_url((osip_from_t*)header,url)
Set the url in the Contact element.
Parameters
header The element to work on.
url The value of the element.
Typedef Documentation
osip_contact_t
Structure for Contact headers.
Function Documentation
int osip_contact_clone (const osip_contact_t * header, osip_contact_t ** dest)
Clone a Contact element.
Parameters
header The element to work on.
dest A pointer on the copy of the element.
References osip_from_clone().
Referenced by osip_dialog_update_route_set_as_uac(), osip_dialog_update_route_set_as_uas(), and osip_message_clone().
void osip_contact_free (osip_contact_t * header)
Free a Contact element.
Parameters
header The element to work on.
References osip_from_free().
Referenced by osip_dialog_free(), osip_dialog_update_route_set_as_uac(), osip_dialog_update_route_set_as_uas(), osip_message_free(), and osip_message_set_contact().
int osip_contact_init (osip_contact_t ** header)
Allocate a Contact element.
Parameters
header The element to work on.
References osip_from_init().
Referenced by osip_message_set_contact().
int osip_contact_parse (osip_contact_t * header, const char * hvalue)
Parse a Contact element.
Parameters
header The element to work on.
hvalue The string to parse.
References osip_from::displayname, and osip_from_parse().
Referenced by osip_message_set_contact().
int osip_contact_to_str (const osip_contact_t * header, char ** dest)
Get a string representation of a Contact element.
Parameters
header The element to work on.
dest A pointer on the new allocated string.
References osip_from::displayname, and osip_from_to_str().