libosip: oSIP authorization header definition.
oSIP authorization header definition.
oSIP headers definitions
Classes
struct osip_authorization
Typedefs
typedef struct osip_authorization osip_authorization_t
Functions
int osip_authorization_init (osip_authorization_t **header)
int osip_authorization_parse (osip_authorization_t *header, const char *hvalue)
int osip_authorization_to_str (const osip_authorization_t *header, char **dest)
void osip_authorization_free (osip_authorization_t *header)
int osip_authorization_clone (const osip_authorization_t *header, osip_authorization_t **dest)
char * osip_authorization_get_auth_type (const osip_authorization_t *header)
void osip_authorization_set_auth_type (osip_authorization_t *header, char *value)
char * osip_authorization_get_username (osip_authorization_t *header)
void osip_authorization_set_username (osip_authorization_t *header, char *value)
char * osip_authorization_get_realm (osip_authorization_t *header)
void osip_authorization_set_realm (osip_authorization_t *header, char *value)
char * osip_authorization_get_nonce (osip_authorization_t *header)
void osip_authorization_set_nonce (osip_authorization_t *header, char *value)
char * osip_authorization_get_uri (osip_authorization_t *header)
void osip_authorization_set_uri (osip_authorization_t *header, char *value)
char * osip_authorization_get_response (osip_authorization_t *header)
void osip_authorization_set_response (osip_authorization_t *header, char *value)
char * osip_authorization_get_digest (osip_authorization_t *header)
void osip_authorization_set_digest (osip_authorization_t *header, char *value)
char * osip_authorization_get_algorithm (osip_authorization_t *header)
void osip_authorization_set_algorithm (osip_authorization_t *header, char *value)
char * osip_authorization_get_cnonce (osip_authorization_t *header)
void osip_authorization_set_cnonce (osip_authorization_t *header, char *value)
char * osip_authorization_get_opaque (osip_authorization_t *header)
void osip_authorization_set_opaque (osip_authorization_t *header, char *value)
char * osip_authorization_get_message_qop (osip_authorization_t *header)
void osip_authorization_set_message_qop (osip_authorization_t *header, char *value)
char * osip_authorization_get_nonce_count (osip_authorization_t *header)
void osip_authorization_set_nonce_count (osip_authorization_t *header, char *value)
Detailed Description
Typedef Documentation
osip_authorization_t
Structure for Authorization headers.
Function Documentation
int osip_authorization_clone (const osip_authorization_t * header, osip_authorization_t ** dest)
Clone a Authorization element.
Parameters
header The element to work on.
dest A pointer on the copy of the element.
References osip_authorization::algorithm, osip_authorization::auth_type, osip_authorization::cnonce, osip_authorization::digest, osip_authorization::message_qop, osip_authorization::nonce, osip_authorization::nonce_count, osip_authorization::opaque, osip_authorization_free(), osip_authorization_init(), osip_authorization::realm, osip_authorization::response, osip_authorization::uri, and osip_authorization::username.
Referenced by osip_message_clone().
void osip_authorization_free (osip_authorization_t * header)
Free a Authorization element.
Parameters
header The element to work on.
References osip_authorization::algorithm, osip_authorization::auth_type, osip_authorization::cnonce, osip_authorization::digest, osip_authorization::message_qop, osip_authorization::nonce, osip_authorization::nonce_count, osip_authorization::opaque, osip_authorization::realm, osip_authorization::response, osip_authorization::uri, and osip_authorization::username.
Referenced by osip_authorization_clone(), osip_message_free(), and osip_message_set_authorization().
char* osip_authorization_get_algorithm (osip_authorization_t * header)
Get value of the algorithm parameter from a Authorization element.
Parameters
header The element to work on.
References osip_authorization::algorithm.
char* osip_authorization_get_auth_type (const osip_authorization_t * header)
Get value of the auth_type parameter from a Authorization element.
Parameters
header The element to work on.
References osip_authorization::auth_type.
char* osip_authorization_get_cnonce (osip_authorization_t * header)
Get value of the cnonce parameter from a Authorization element.
Parameters
header The element to work on.
References osip_authorization::cnonce.
char* osip_authorization_get_digest (osip_authorization_t * header)
Get value of the digest parameter from a Authorization element.
Parameters
header The element to work on.
References osip_authorization::digest.
char* osip_authorization_get_message_qop (osip_authorization_t * header)
Get value of the message_qop parameter from a Authorization element.
Parameters
header The element to work on.
References osip_authorization::message_qop.
char* osip_authorization_get_nonce (osip_authorization_t * header)
Get value of the nonce parameter from a Authorization element.
Parameters
header The element to work on.
References osip_authorization::nonce.
char* osip_authorization_get_nonce_count (osip_authorization_t * header)
Get value of the nonce_count parameter from a Authorization element.
Parameters
header The element to work on.
References osip_authorization::nonce_count.
char* osip_authorization_get_opaque (osip_authorization_t * header)
Get value of the opaque parameter from a Authorization element.
Parameters
header The element to work on.
References osip_authorization::opaque.
char* osip_authorization_get_realm (osip_authorization_t * header)
Get value of the realm parameter from a Authorization element.
Parameters
header The element to work on.
References osip_authorization::realm.
char* osip_authorization_get_response (osip_authorization_t * header)
Get value of the response parameter from a Authorization element.
Parameters
header The element to work on.
References osip_authorization::response.
char* osip_authorization_get_uri (osip_authorization_t * header)
Get value of the uri parameter from a Authorization element.
Parameters
header The element to work on.
References osip_authorization::uri.
char* osip_authorization_get_username (osip_authorization_t * header)
Get value of the username parameter from a Authorization element.
Parameters
header The element to work on.
References osip_authorization::username.
int osip_authorization_init (osip_authorization_t ** header)
Allocate a Authorization element.
Parameters
header The element to work on.
Referenced by osip_authorization_clone(), and osip_message_set_authorization().
int osip_authorization_parse (osip_authorization_t * header, const char * hvalue)
Parse a Authorization element.
Parameters
header The element to work on.
hvalue The string to parse.
References osip_authorization::algorithm, osip_authorization::auth_type, osip_authorization::cnonce, osip_authorization::digest, osip_authorization::message_qop, osip_authorization::nonce, osip_authorization::nonce_count, osip_authorization::opaque, osip_authorization::realm, osip_authorization::response, osip_authorization::uri, and osip_authorization::username.
Referenced by osip_message_set_authorization().
void osip_authorization_set_algorithm (osip_authorization_t * header, char * value)
Add the algorithm parameter from a Authorization element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authorization::algorithm.
void osip_authorization_set_auth_type (osip_authorization_t * header, char * value)
Add the auth_type parameter from a Authorization element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authorization::auth_type.
void osip_authorization_set_cnonce (osip_authorization_t * header, char * value)
Add the cnonce parameter from a Authorization element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authorization::cnonce.
void osip_authorization_set_digest (osip_authorization_t * header, char * value)
Add the digest parameter from a Authorization element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authorization::digest.
void osip_authorization_set_message_qop (osip_authorization_t * header, char * value)
Add the message_qop parameter from a Authorization element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authorization::message_qop.
void osip_authorization_set_nonce (osip_authorization_t * header, char * value)
Add the nonce parameter from a Authorization element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authorization::nonce.
void osip_authorization_set_nonce_count (osip_authorization_t * header, char * value)
Add the nonce_count parameter from a Authorization element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authorization::nonce_count.
void osip_authorization_set_opaque (osip_authorization_t * header, char * value)
Add the opaque parameter from a Authorization element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authorization::opaque.
void osip_authorization_set_realm (osip_authorization_t * header, char * value)
Add the realm parameter from a Authorization element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authorization::realm.
void osip_authorization_set_response (osip_authorization_t * header, char * value)
Add the response parameter from a Authorization element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authorization::response.
void osip_authorization_set_uri (osip_authorization_t * header, char * value)
Add the uri parameter from a Authorization element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authorization::uri.
void osip_authorization_set_username (osip_authorization_t * header, char * value)
Add the username parameter from a Authorization element.
Parameters
header The element to work on.
value The value of the new parameter.
References osip_authorization::username.
int osip_authorization_to_str (const osip_authorization_t * header, char ** dest)
Get a string representation of a Authorization element.
Parameters
header The element to work on.
dest A pointer on the new allocated string.
References osip_authorization::algorithm, osip_authorization::auth_type, osip_authorization::cnonce, osip_authorization::digest, osip_authorization::message_qop, osip_authorization::nonce, osip_authorization::nonce_count, osip_authorization::opaque, osip_authorization::realm, osip_authorization::response, osip_authorization::uri, and osip_authorization::username.