libosip: oSIP mutex definitions
oSIP mutex definitions
Classes
struct osip_mutex
Functions
struct osip_mutex * osip_mutex_init (void)
void osip_mutex_destroy (struct osip_mutex *mut)
int osip_mutex_lock (struct osip_mutex *mut)
int osip_mutex_unlock (struct osip_mutex *mut)
Detailed Description
Function Documentation
void osip_mutex_destroy (struct osip_mutex * mut)
Destroy the mutex.
Parameters
mut The mutex to destroy.
Referenced by osip_fifo_free(), and osip_release().
struct osip_mutex* osip_mutex_init (void) read
Allocate and Initialise a mutex.
Referenced by osip_fifo_init(), and osip_init().
int osip_mutex_lock (struct osip_mutex * mut)
Lock the mutex.
Parameters
mut The mutex to lock.
Referenced by osip_fifo_add(), osip_fifo_get(), osip_fifo_insert(), osip_fifo_size(), osip_fifo_tryget(), osip_ict_execute(), osip_ist_execute(), osip_nict_execute(), osip_nist_execute(), osip_timers_gettimeout(), osip_timers_ict_execute(), osip_timers_ist_execute(), osip_timers_nict_execute(), and osip_timers_nist_execute().
int osip_mutex_unlock (struct osip_mutex * mut)
Unlock the mutex.
Parameters
mut The mutex to unlock.
Referenced by osip_fifo_add(), osip_fifo_get(), osip_fifo_insert(), osip_fifo_size(), osip_fifo_tryget(), osip_ict_execute(), osip_ist_execute(), osip_nict_execute(), osip_nist_execute(), osip_timers_gettimeout(), osip_timers_ict_execute(), osip_timers_ist_execute(), osip_timers_nict_execute(), and osip_timers_nist_execute().