libosip: oSIP from header definition.
oSIP from header definition.
oSIP headers definitions
Classes
struct osip_from
Macros
#define osip_from_param_add(header, name, value) osip_generic_param_add((&(header)->gen_params),name,value)
#define osip_from_param_get_byname(header, name, dest) osip_generic_param_get_byname((&(header)->gen_params),name,dest)
#define osip_from_get_tag(header, dest) osip_generic_param_get_byname((&(header)->gen_params), "tag",dest)
#define osip_from_set_tag(header, value) osip_generic_param_add((&(header)->gen_params), osip_strdup("tag"),value)
Typedefs
typedef struct osip_from osip_from_t
Functions
int osip_from_init (osip_from_t **header)
void osip_from_free (osip_from_t *header)
int osip_from_parse (osip_from_t *header, const char *hvalue)
int osip_from_to_str (const osip_from_t *header, char **dest)
int osip_from_clone (const osip_from_t *header, osip_from_t **dest)
void osip_from_set_displayname (osip_from_t *header, char *value)
char * osip_from_get_displayname (osip_from_t *header)
void osip_from_set_url (osip_from_t *header, osip_uri_t *url)
osip_uri_t * osip_from_get_url (osip_from_t *header)
int osip_from_param_get (osip_from_t *header, int pos, osip_generic_param_t **dest)
int osip_from_tag_match (osip_from_t *from1, osip_from_t *from2)
Detailed Description
Macro Definition Documentation
#define osip_from_get_tag (header, dest) osip_generic_param_get_byname((&(header)->gen_params), "tag",dest)
Find the tag parameter in a From element.
Parameters
header The element to work on.
dest A pointer on the element found.
Referenced by osip_dialog_match_as_uac(), and osip_dialog_match_as_uas().
#define osip_from_param_add (header, name, value) osip_generic_param_add((&(header)->gen_params),name,value)
Allocate and add a generic parameter element in a list.
Parameters
header The element to work on.
name The token name.
value The token value.
#define osip_from_param_get_byname (header, name, dest) osip_generic_param_get_byname((&(header)->gen_params),name,dest)
Find a header parameter in a From element.
Parameters
header The element to work on.
name The token name to search.
dest A pointer on the element found.
Referenced by osip_from_tag_match().
#define osip_from_set_tag (header, value) osip_generic_param_add((&(header)->gen_params), osip_strdup("tag"),value)
Allocate and add a tag parameter element in a Contact element.
Parameters
header The element to work on.
value The token value.
Typedef Documentation
osip_from_t
Structure for From headers.
Function Documentation
int osip_from_clone (const osip_from_t * header, osip_from_t ** dest)
Clone a From element.
Parameters
header The element to work on.
dest A pointer on the copy of the element.
References osip_from::displayname, osip_from::gen_params, osip_from_free(), osip_from_init(), osip_generic_param_clone, osip_list_clone(), osip_uri_clone(), and osip_from::url.
Referenced by osip_contact_clone(), osip_message_clone(), and osip_to_clone().
void osip_from_free (osip_from_t * header)
Free a From element.
Parameters
header The element to work on.
References osip_from::displayname, osip_from::gen_params, osip_uri_free(), and osip_from::url.
Referenced by osip_contact_free(), osip_dialog_free(), osip_from_clone(), osip_message_free(), osip_message_set_from(), osip_record_route_free(), osip_route_free(), osip_to_free(), and osip_transaction_free2().
char* osip_from_get_displayname (osip_from_t * header)
Get the displayname from a From header.
Parameters
header The element to work on.
References osip_from::displayname.
osip_uri_t* osip_from_get_url (osip_from_t * header)
Get the url from a From header.
Parameters
header The element to work on.
References osip_from::url.
int osip_from_init (osip_from_t ** header)
Allocate a From element.
Parameters
header The element to work on.
References osip_list_init().
Referenced by osip_contact_init(), osip_from_clone(), osip_message_set_from(), osip_record_route_init(), osip_route_init(), and osip_to_init().
int osip_from_param_get (osip_from_t * header, int pos, osip_generic_param_t ** dest)
Get a header parameter from a From element.
Parameters
header The element to work on.
pos The index of the element to get.
dest A pointer on the element found.
References osip_from::gen_params, osip_list_get(), and osip_list_size().
int osip_from_parse (osip_from_t * header, const char * hvalue)
Parse a From element.
Parameters
header The element to work on.
hvalue The string to parse.
References osip_from::displayname, osip_from::gen_params, osip_uri_init(), osip_uri_parse(), and osip_from::url.
Referenced by osip_contact_parse(), osip_message_set_from(), osip_record_route_parse(), osip_route_parse(), and osip_to_parse().
void osip_from_set_displayname (osip_from_t * header, char * value)
Set the displayname in the From element.
Parameters
header The element to work on.
value The value of the element.
References osip_from::displayname.
void osip_from_set_url (osip_from_t * header, osip_uri_t * url)
Set the url in the From element.
Parameters
header The element to work on.
url The value of the element.
References osip_from::url.
int osip_from_tag_match (osip_from_t * from1, osip_from_t * from2)
Check if the tags in the From headers match. NOTE: THIS IS AN INTERNAL METHOD ONLY
Parameters
from1 The first From header.
from2 The second From header.
References osip_uri_param::gvalue, and osip_from_param_get_byname.
Referenced by osip_to_tag_match().
int osip_from_to_str (const osip_from_t * header, char ** dest)
Get a string representation of a From element.
Parameters
header The element to work on.
dest A pointer on the new allocated string.
References osip_from::displayname, osip_from::gen_params, osip_uri_param::gname, osip_uri_param::gvalue, osip_list_eol(), osip_list_get(), osip_uri_to_str(), and osip_from::url.
Referenced by osip_contact_to_str(), and osip_to_to_str().